language: c

compiler:
  - gcc

script: make -C projects/linux clean all && make -C projects/linux/host clean all

notifications:
  email:
    recipients:
      - jcd@tribudubois.net
  on_success: change
  on_failure: always
