language: c
compiler:
  - gcc
  - clang
script: make -C projects/linux && make -C projects/linux/hosts
notifications:
  email:
    recipients:
      - jcd@tribudubois.net
    on_success: change
    on_failure: always
